general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

# Lock the screen
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

listener {
    timeout = 150                                # 2.5min
    on-timeout = brightnessctl -d "intel_backlight" set 10%           # dim monitor
    on-resume = brightnessctl -d "intel_backlight" set 75%           # restore brightness
}

# Turn off screen
listener {
    timeout = 420
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Suspend the system
# Suspend the system (Only if NOT on AC power)
listener {
    timeout = 600
    on-timeout = [ $(cat /sys/class/power_supply/AC/online) -eq 0 ] && systemctl suspend
}
