background {
    monitor =
    # 'screenshot' is a special keyword; it doesn't leave a file behind!
    path = screenshot 
    
    blur_passes = 3 
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.6 # Dimming helps with UI visibility
    vibrancy = 0.1696
}

general {
    no_fade_in = false
    # 'grace = 0' means it locks instantly. 
    # Set to 2-3 if you want a few seconds to move the mouse and cancel.
    grace = 0 
    disable_loading = true
}

# [Optional] TIME DISPLAY
label {
    monitor =
    text = $TIME
    color = rgba(255, 255, 255, 0.8)
    font_size = 100
    font_family = JetBrains Mono Nerd Font
    position = 0, 150
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0.5) # Darker semi-transparent box
    font_color = rgb(200, 200, 200)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    hide_input = false
    position = 0, -20
    halign = center
    valign = center
}
